# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn backend:build
    
    - name: Release 
      uses: ncipollo/release-action@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        artifacts: "backend/bundle/*"
        prerelease: ${{ endsWith(github.ref, 'rc') || endsWith(github.ref, 'snapshot') }}
        token: ${{ secrets.GITHUB_TOKEN }}
