# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'yarn'

    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn frontend:build

    - name: Deploy to GitHub-Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      # Only deploy if it's on the master branch
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: frontend/dist # The folder the action should deploy.
